name: Instagram Altin Botu

on:
  schedule:
    # Saatler UTC formatındadır. TSİ için 3 saat çıkarın.
    # 07:00 (10:00 TSİ), 11:00 (14:00 TSİ), 15:00 (18:00 TSİ)
    - cron: '0 7,11,15 * * *'
  workflow_dispatch: # İstediğinizde manuel çalıştırmak için

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pillow pytz

      - name: Run Bot
        env:
          INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
          INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
        run: python bot.py
